### ISSUE TITLE
[Soft release] Address book not migrated on Firefox browser

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#1040]
## Bug description
The address book from the legacy interface (https://gnosis-safe.io/) is not bbeing migrated to the new one (https://app.safe.global/) on Firefox. As discussed internally, this might be due to some security restrictions with the browser

## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: Mainnet

## Steps to reproduce
 1. Make sure you have entries on the address book / local storage on the legacy web interface
 2. Open the new web interface for the first time

## Expected result
Entries are migrated (this is all bueno in Chrome at the moment).

## Obtained result
Entries are not migrated.

**Comment by schmanu** [comment]
## Summary
The access to the local storage of `gnosis-safe.io` from an iframe embedded at `app.safe.global` is blocked by Firefox with Dynamic State Partitioning enabled, which is the current default.

### Details
To prevent tracking and increase privacy Firefox partitions some dynamic state which includes the `localStorage`.
In order to access it we would have to call `document.requestStorageAccess` before accessing the `localStorage` from the `/app/migrate.html` iframe. 

Currently we communicate without user interaction using messages sent between the parent window and iframe.
If we try to call `document.requestStorageAccess` before accessing the localStorage when a migration message is received we run into this error: `document.requestStorageAccess() may only be requested from inside a short running user-generated event handler`

The only solution would be to embed some button in the iframe and migrate once the user clicks on it. This is not how the migration is intended to work though and would break the flow.

So for now I will close this issue as not fixable.

#### Links
- https://developer.mozilla.org/en-US/docs/Web/Privacy/Storage_Access_Policy/Errors/CookiePartitionedForeign
- https://developer.mozilla.org/en-US/docs/Web/Privacy/State_Partitioning

### Workaround
Luckily there is a workaround which we could promote to users with a lot of safes who do not want to manually migrate everything.
1. Navigate to `about:config` to access the Firefox Advanced Preferences and set `network.cookie.cookieBehavior` to `4`. 
2. Clear the localStorage for `https://app.safe.global` 
3. Navigate to `https://app.safe.global` 
4. Migration should now have worked successfully
5. (optional) Set `network.cookie.cookieBehavior` back to `5`
