### ISSUE TITLE
[Soft release] Load Safe crashes when clicking "continue" too fast

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1055]
## Bug description
While loading an existing safe from the sidebar, clicking the continue button from the step 2 too fast causes the page to crash. 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli
 - Env: https://app.safe.global/

#1039 

## Steps to reproduce
 1. Connect with an owner that already has safes created in the network
 2. Select any of them that you never loaded before
 3. Then open the sidebar again and the "Add Safe" option is now available. click it
 4. Once in step 2, click the "Continue" button 2 or more times really quickly

## Obtained result
![crash](https://user-images.githubusercontent.com/4503659/199871700-524d533c-7751-4608-aabd-9a4c4928092b.gif)

**Comment by francovenica** [comment]
The error message 
![image](https://user-images.githubusercontent.com/4503659/199871797-711b8c18-c7e3-4142-87c8-7c78901f3f18.png)

**Comment by iamacook** [comment]
After looking into this, the error occurs on the `SafeOwnersStep` because `params` is not populated with `owners`. The following seems to fix it:

![image](https://user-images.githubusercontent.com/20442784/199957009-11d5e4eb-1ed7-4f6a-acf5-0c33b1fb231c.png)

However, I think this is a) an edge case and b) a much deeper problem with our current `useTxStepper` implementation. Whilst the above "fixes" the problem, it results in the following:

![fast-click](https://user-images.githubusercontent.com/20442784/199956849-f0c2b928-e0ab-4cf4-b8b4-cce23feeac88.gif)

I personally think that an error makes much more sense for the time being over an unresponsive page. The likelihood someone immediately clicks through all steps is very low.

As we are reworking the Safe creation flow and very soon the load one as well, I would categorise this as "won't fix" and use this to improve the new stepper hook. The `merge` logic is not working as expected because the subsequent forms do not mount in time:

![image](https://user-images.githubusercontent.com/20442784/199959221-b6531703-7c21-4806-bdc7-e8d752d4a968.png)

I am not sure how to best handle this and/or if it's possible with form validation as they don't mount in time. I think we need to look into our `activeStep` incrementing and whether we should me merging values into an empty `defaultValues` object that contains empty values for _all_ fields in the stepper.

**Comment by francovenica** [comment]
I agree with the won't fix, especially since we will change the safe creation/load workflow.
I'd suggest for those new flows disable the button once the user clicks continue so there is no chance for multiple clicking
