### ISSUE TITLE
Custom safeTxGas is not used for simulations

### ISSUE THREAD

**Issue by usame-algan** [safe-global/web-core#1294]
## Bug description

The transaction simulation is always using the default `safeTxGas`.

## Steps to reproduce
 1. Go to a 1.1.1 safe
 2. Create a transaction
 3. Observe that a `safeTxGas` value is visible in the params
 4. Press Simulate
 5. Check that the transaction data contains the same `safeTxGas` amount
 6. Open the params and change the `safeTxGas` value
 7. Press Simulate again
 8. Observe that the transaction data still contains the default `safeTxGas` amount

## Screenshots

<img width="626" alt="Screenshot 2022-11-30 at 18 45 27" src="https://user-images.githubusercontent.com/5880855/204870275-dbed319b-0bfc-41fa-b961-0d4020a71039.png">
<img width="526" alt="Screenshot 2022-11-30 at 18 45 43" src="https://user-images.githubusercontent.com/5880855/204870328-f9dfe283-f3c7-4503-be9e-92a343be1c1f.png">

**Comment by giacomolicari** [comment]
Hi :wave:
it seems we are still experiencing the issue on Gnosis Chain in [this Safe transaction](https://app.safe.global/gno:0x7a48Dac683DA91e4faa5aB13D91AB5fd170875bd/transactions/tx?id=multisig_0x7a48Dac683DA91e4faa5aB13D91AB5fd170875bd_0x0e3421a1396c4e0d45e1bf9884d4fca6521cd1246cfedf2b62a93982319b0d0e).

When I create the transaction using the Transaction Builder I get the [following simulation](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/fa525e96-0222-46e6-99c0-9a6744a8e933/logs) which returns an overall ExecutionSuccess event.

Hovever when I publish the transaction, safeTxGas gets automatically calculated and now that I’m about to execute the transaction I get the [following simulated result](https://dashboard.tenderly.co/public/safe/safe-apps/simulator/3076a15b-a3f7-4ffe-b768-2ecf603b0da8/logs), which fails because of lack of gas.

Is there a way to execute the transaction I’ve already created without need for replacing it with another one?

**Comment by katspaugh** [comment]
Thanks @giacomolicari, we’ll look into it.

**Comment by usame-algan** [comment]
@giacomolicari I tried reproducing the issue without success in a 1.3.0 safe. There is a `changeMasterCopy` call as part of the failed transaction which afaik is only available in older safe contracts where we estimate `safeTxGas`. Was the safe in question upgraded recently?

**Comment by giacomolicari** [comment]
Hi @usame-algan ,
yes we recently upgraded the master copy to v1.3.0, the transaction replaced the failing one containing wrong safeTxGas.

I'll close the issue since probably it was due to the old version of the contracts, thank you for the support.

**Comment by DiogoSoaress** [comment]
The original issue was fixed with https://github.com/safe-global/web-core/pull/1439

@giacomolicari 's report has to do with the Tx Builder not doing a gas estimation (passes 0 `safeTxGas`). This simulation is different from the one in the review transaction modal, which includes the gas estimation.

It happens often that the gas estimation in Gnosis Chain is too low which resulted in the simulation to fail.

**Comment by giacomolicari** [comment]
Hi @DiogoSoaress ,
I think we can close this issue for the moment, we haven't experienced the issue since we upgraded the contracts to v1.3.0. I'll re-open the case if we should face the issue again. thank you!

**Comment by DiogoSoaress** [comment]
The discrepancy between simulations comes from TxBuilder's simulation not considering `safeTxGas` so I suggest opening an issue in that repo if we face this issue again. I'm closing the current issue given these findings. Thanks for the detailed report Giacomo.
