### ISSUE TITLE
[EIP-1271] Can't get off chain modal to show up

### ISSUE THREAD

**Issue by francovenica** [safe-global/web-core#1413]
## Bug description
Tried to create an off-chain type of signature but I always get the on-chain modal to sign

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: goerli
 - Env: https://eip_1271--webcore.review-web-core.5afe.dev/gor:0x8FE062e9b0865dc47552415a745CEEe392eFb6C3
 - WC app used as custom: https://pr608--safereactapps.review-react-hr.5afe.dev/wallet-connect/

## Steps to reproduce
 1. Started the Test app, http://localhost:5173/
 2. Opened the epic branch on web app
 3. Added the Wallet connect app as custom app
 4. Connected both apps
 5. Enabled off-chain type of message
 6. Wrote a message and used the "sign" button
 7. Checked the web app waiting for the offchain type of modal

## Expected result
Get the offchain type of modal

## Obtained result
I always get the on-chain type of modal, and an error in the console (no errors in the network tab)

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/208892915-37590015-d7ca-41c3-85aa-f469ffe86e15.png)

**Comment by liliya-soroka** [comment]
The case when I am also getting on-chain message instead of expected off-chain:
1. connect WC and testDapp
2. try off-chain message -> close Confirm off-chain message modal 
3. go from the WC app to the transactions ( actions inside the same tab)
4. come back to the safe apps-> WC
5. try to create an off-chain message again
Current result: On-chain message modal always appears till the WC and testDapp are reconnected.

The workaround that works for me but does not work for Franco( we have tried it together):
1. Disconnect WC and testDapp
2. reconnect ->Enable off-chain sign and click sign in testDapp
Current result: off-chain message modal appears again as expected

Description: if the WC is opened with a previously established connection to the test Dapp, on-chain messages are always generated instead of off-chain.

**Comment by francovenica** [comment]
Ok, the reason why for me was always failing is because my safe, for some reason, didn't have fallbackHandler set, which is an important part for processing signatures
I added a fallbackHandler to my safe using the MasterCopy ABI and now I can see the off-chain signature modal
![image](https://user-images.githubusercontent.com/4503659/208925482-f76d927b-2d91-4b8a-b1cd-02e3f4f01ca9.png)
