### ISSUE TITLE
Sepolia support

### ISSUE THREAD

**Issue by ligi** [safe-global/web-core#1550]
Jamie originally opened this issue here: https://github.com/safe-global/safe-react/issues/4139
but it is now gone - so opening it again.
Sepolia is the new testnet for apps - - see e.g. @q9f 's talk from https://github.com/efdevcon here:  https://archive.devcon.org/archive/watch/6/post-merge-testnets

![image](https://user-images.githubusercontent.com/111600/212740429-9e8ea323-8d1f-4bde-bc52-b5e9cd6a3d4c.png)

see also : https://blog.ethereum.org/2022/06/21/testnet-deprecation

**Comment by katspaugh** [comment]
This is the repo for the web front end, so I'll mark it as blocked and share it with the infra team. The entire stack for Sepolia would have to be created, not just the UI.

**Comment by katspaugh** [comment]
cc @FahdSaif – please feel free to move this issue and track it on the infra side.

**Comment by katspaugh** [comment]
I'm copying @jpitt's original issue here because issues are disabled in the legacy safe-react repo:

## Overview

Requesting the addition of Sepolia testnet to the Safe user interface. 

Goerli is the only testnet appearing in the user interface, yet Sepolia is also a recommended testnet. Currently, Sepolia is [recommended](https://ethereum.org/en/developers/docs/networks/#sepolia) for application developers, whereas Goerli is recommended for testing validation and staking. Also, the v1.3.0 Safe contracts have already been deployed to Sepolia (see: [Sepolia Etherscan](https://sepolia.etherscan.io/address/0x69f4D1788e39c87893C980c06EdF4b7f686e2938#code) and [Safe deployment config file](https://github.com/safe-global/safe-deployments/blob/main/src/assets/v1.3.0/gnosis_safe.json) w/ Sepolia network ID 11155111).

EF Devops would specifically like to have this added so that the tokens for permissioned sepolia validators can be conveniently managed by the team members using the Safe dapp. It is also critical for application developers in the community to have Sepolia added in order to test with Safe.

## Requirements

- UX changes to safe-react
- Changes to safe-transaction-service
- Deployment of safe-transaction-service
- Update this [list of supported networks](https://help.gnosis-safe.io/en/articles/6227806-supported-networks)

_Please let me know if there is a need to have the transaction service supported or run, or if deploying the service is not feasible for some reason._

## Designs

In the drop-down, perhaps use the dayglo green lettering on dark grey background (as used on the [Sepolia info website](https://sepolia.dev/)). It should go above or below Goerli.

<img width="145" alt="image" src="https://user-images.githubusercontent.com/509756/208078998-72fc9d03-2642-436e-b09b-d0a56735de8b.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/509756/208079400-048324ce-5ad9-4eb3-a244-1a7eac219d15.png">

## Links

[Feb 2020 request for Goerli Testnet Version](https://github.com/safe-global/safe-react/issues/600) Issue https://github.com/safe-global/safe-react/issues/600

[General info about Sepolia testnet](https://github.com/eth-clients/sepolia)

**Comment by liliya-soroka** [comment]
Most likely we will go with support Holesovice by the end of 2023 instead of Goerli https://ethereum-magicians.org/t/proposal-predictable-ethereum-testnet-lifecycle/11575 
There is no plan to add Sepolia as a test network

**Comment by katspaugh** [comment]
Closing this, since chain support is added on the backend, not frontend, and we don't need to track it here.
