### ISSUE TITLE
[Polygon]the error "call revert exception " appears on tx signing/execution on polygon 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#1748]
## Bug description
Sometimes the error "call revert exception " appears on tx signing/execution on polygon 
The issue was reported here - https://github.com/5afe/safe-support/issues/154 , but I am also facing the error from time to time using my MM owner. But it's possible to sign/execute the tx when you try to restart the process a few times
## Environment
 - Browser: Chrome
 - Wallet: MetaMask/ any
 - Chain: Polygon

## Steps to reproduce
1. create a tx
2. try to sign or execute it as the second owner 
Current result: The error appears. restart the process a few times and you will be able to sign /execute the tx

## Expected result
make sure that the owner is able to sign and execute the tx 
## Screenshots
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/338622/223455468-8b36b030-c969-457c-9b5d-2b7b38b1fbd5.png">

**Comment by katspaugh** [comment]
Manu says: Infura changed something in their API key permissions, so L2s might stop working with old API keys.

**Comment by iamacook** [comment]
We still think this is likely an RPC issue. We will investigate it, timeblocked to an hour, and summarise our research for a (won't) fix.

**Comment by iamacook** [comment]
In order to transact, we require ~7 `eth_call` calls to get the threshold, owners, etc. and some RPC providers prevent/limit successive `eth_call` calls. As such, I've contacted our current RPC provider (`polygon-rpc.com`) to see if they do this. We will otherwise need to switch to another (and somehow inform users with the current network config?).

A potential alternative which MetaMask uses as their default is `polygon-mainnet.infura.io` _without_ an API key.

**Comment by iamacook** [comment]
After [discussing this at length with the team](https://5afe.slack.com/archives/C04D6FYP6G0/p1681719422968769), we're going to close this as "won't fix" and will reassess it if we can consistently replicate the issue/we receive further complaints.
