### ISSUE TITLE
[Batch execution] More user friendly txs info is missing on the Batch execution review screen

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/web-core#662]
## Bug description
More user friendly txs info is missed on the Batch execution review screen
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: rinkeby

## Steps to reproduce
 1. Go to https://web-core.pages.dev/rin:0xf2565317F3Ae8Ae9EA98E9Fe1e7FADC77F823cbD/transactions/queue
 2. click execute batch txs
 3. check review screen
 Current result: 
There is tx details but no proper decoded info about each tx 
<img width="613" alt="image" src="https://user-images.githubusercontent.com/338622/192318742-da44e883-35f2-40fd-946f-3e543638263a.png">

## Expected result
we should keep proper user-friendly tx details for batch txs, as we have on safe-react
<img width="561" alt="image" src="https://user-images.githubusercontent.com/338622/192318866-5e7577e6-e791-44d8-bed6-b3ac57ba0aa6.png">

**Comment by katspaugh** [comment]
1. Enhance the Details to show "Contract interaction" etc
2. Expand them by default
3. Check how TxBuilder is doing it

**Comment by francovenica** [comment]
The details looks good, but we should make the section scrollable horizontally because some data are just too long.
Also I had issues with name of parameters been too long and falling to the next line
![image](https://user-images.githubusercontent.com/4503659/193939912-7823e1b7-aa05-4682-907f-cae2920830f3.png)
![image](https://user-images.githubusercontent.com/4503659/193939929-2ddff8dc-7a71-4a0e-a431-423ad92bbd6b.png)

To recreate this you can use this rinkeby dummy contract in the safe Tx app, and just adding some valid inputs
0x49d4450977E2c95362C13D3a31a09311E0Ea26A6

**Comment by francovenica** [comment]
The issues just UI related so we can pass the ticket since the main issue of tx details was solved
