### ISSUE TITLE
[Safe apps list] Added custom app present under all apps

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#693]
## Description
Adding a custom app will include it under the 'all apps' section

## Steps to reproduce
Add a custom app like [Snaphot](https://snapshot.org/) on Rinkeby.

## Expected result
App present as a custom app only.

## Obtained result
App present as a custom app as expected but also in the all apps list which is unexpected as it seems it is managed by us. Small video of the process:

https://user-images.githubusercontent.com/92332710/192529006-68789c9c-086f-425a-bc51-5b71bf92a63d.mp4

**Comment by clemoon** [comment]
Checked with Tanya on this and we're both of the opinion that this is the expected behaviour. Adding a custom app to safe apps section should also add this app to the "all" list. Currently the "all" list displays the applications in alphabetical order and that could be suboptimal, but this re-definition should be part of another epic/issue
