### ISSUE TITLE
[Polygon] Transactions failing with default gas parameters

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/web-core#781]
## Bug description
I am not able to execute a transaction on my 1/2 test safe.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Polygon

## Steps to reproduce
 1. Try to execute this [transaction](https://web-core.pages.dev/matic:0x6D04edC44F7C88faa670683036edC2F6FC10b86e/transactions/tx?id=multisig_0x6D04edC44F7C88faa670683036edC2F6FC10b86e_0x4731121fcf88a898abedc40234fd15f720b81e8a1c051f32d61a53bf1aba57ff) without touching fee parameters or mm gas fee

## Expected result
Transaction executed successfully.

## Obtained result
No bueno. A couple of examples.

Send from web:

https://user-images.githubusercontent.com/92332710/193256688-6b5ba870-3451-4f6c-bb3f-9ff7f20f5033.mp4

Batched tx from tx-builder

https://user-images.githubusercontent.com/92332710/193256764-130c13e2-c1e0-4bb3-b664-0c6a19e4a393.mp4

Manually editing the priority on mm after submitting the tx is doing the trick for me.

**Comment by katspaugh** [comment]
Polygon on the whole and our Polygon services in particular weren't doing well in the last few days, but now they seem to be good.

**Comment by JagoFigueroa** [comment]
Just checked and confirm that the issue with gas estimation persists on the revamp :( On legacy it is all bueno.

**Comment by katspaugh** [comment]
I see, thanks Jago 👍

**Comment by iamacook** [comment]
`FEATURES.EIP1559` not correctly checked in all places. I onlys see it being used in `SignOrExecuteForm` and `ReviewSpendingLimit`. Perhaps this is related?

**Comment by katspaugh** [comment]
@iamacook everything is fine with EIP-1559 on Polygon. Polygon supports that. It's a problem on Optimism tho.

**Comment by iamacook** [comment]
[We use `ethers`' `getFeeData` to estimate EIP-1559 values](https://github.com/safe-global/web-core/blob/dev/src/hooks/useGasPrice.ts#L69). It returns a [hardcoded `maxPriorityFeePerGas`](https://github.com/ethers-io/ethers.js/blob/master/packages/abstract-provider/src.ts/index.ts#L252) which is **not** high enough for Polygon. This is an [open `ethers` issue](https://github.com/ethers-io/ethers.js/issues/3370). Until this is resolved, we will disable EIP-1559 on Polygon instead of hardcoding a `maxPriorityFeePerGas` instead.

Note: we did not encounter this issue in `safe-react` because [we were using `web3`](https://github.com/safe-global/safe-react/blob/dev/src/logic/wallets/ethTransactions.ts#L33-L65) (which included hardcoded values).

- [Polygon documentation regarding EIP-1559 transactions](https://wiki.polygon.technology/docs/develop/eip1559-transactions/how-to-send-eip1559-transactions/#sending-eip1559-transactions)
- [Underpriced transactions discussion on `ethers`' GitHub](https://github.com/ethers-io/ethers.js/discussions/3018)
- [Suggested (hardcoded) workarounds on `ethers`' GitHub](https://github.com/ethers-io/ethers.js/issues/2828)
- [Initial Polygon investigation findings on Slack](https://5afe.slack.com/archives/C03DAGWJCR5/p1665069918128479)
- [EIP-1559 oracle requirements resulting in decision on Slack](https://5afe.slack.com/archives/C03DAGWJCR5/p1665130520215759)
