### ISSUE TITLE
[Smart contract wallets] On-chain signatures are over confirmed

### ISSUE THREAD

**Issue by katspaugh** [safe-global/web-core#938]
## Bug description
When signing on-chain as a smart contract wallet, the signature isn't being picked up by the backend, and an already executed tx is displayed as not fully signed in the history.

@francovenica writes:

I have a tx from 2 days ago in the history tab that still shows the 2 out of 1
https://dont-propose-on-chain-signat.web-core.pages.dev/gor:0x95ddA5dc54331a1E6B65aF1Cd7167962A2f7f280/transactions/tx?id=multisig_0x95ddA5dc54331a1E6B65aF1Cd7167962A2f7f280_0x51e7aa84f6684a6616c46b301af56c089a7c1d09cc9f10c0dac5f563f2db4ff8

Also this is the latest tx, with nonce 5.
It shows that it requires 1 confirmation (makes sense, threshold was changed to 1 needed) but still has the 2 confirmations registered in the backend:
![image](https://user-images.githubusercontent.com/4503659/196487955-a13c7dbf-babd-4bd0-90b0-7dcd87d91d8d.png)

## Expected result
All required signatures are present.

**Comment by francovenica** [comment]
For more context about the tx in the snapshot.
Is a tx created when the safe needed only 1 signer. The safe has 2 owners, a regular MM account and a safe as owner.
The tx was created and fully singed by the MM account. The Safe was used only to execute that tx.
Still instead of just executing it, a confirmation was added to that tx.

This is the tx:
https://dont-propose-on-chain-signat.web-core.pages.dev/gor:0x95ddA5dc54331a1E6B65aF1Cd7167962A2f7f280/transactions/tx?id=multisig_0x95ddA5dc54331a1E6B65aF1Cd7167962A2f7f280_0x0efe0caa5ee9696876f62197690db01561856ef4f0f679b127adbee71cd25990

This is the Safe-as-owner gor:0x12A9ce973D9b8DA345E77Cd5D0E07186A864E1D2

**Comment by usame-algan** [comment]
I am able to reproduce this with the following steps:

1. Create a new tx in a 1/n safe with a smart contract wallet
2. The tx should have 0 of 1 confirmations
3. Sign the tx with an EOA wallet
4. The tx should have 1 of 1 confirmations
5. Execute the `approveHash` tx in the smart contract wallet
6. The tx displays 2 of 1 confirmations

Technically, this is correct and I think it is not possible to prevent this because of the asynchronous nature of this flow. Displaying 2 of 2 or 1 of 1 in the UI would be misleading imo as the safe is still a 1/n threshold.

**Comment by katspaugh** [comment]
Sounds fair, closing then 👍
